INSERT INTO Genres (name)
VALUES ('Fantasy'),
       ('Self-Help'),
       ('Art'),
       ('Design'),
       ('Horror'),
       ('Science Fiction'),
       ('Non-Fiction'),
       ('Mystery'),
       ('Biography'),
       ('History'),
       ('Children’s Literature'),
       ('Young Adult'),
       ('Classics'),
       ('Poetry'),
       ('Drama'),
       ('Philosophy'),
       ('Science'),
       ('Health & Fitness'),
       ('Business'),
       ('Cookbooks'),
       ('Travel'),
       ('Humor'),
       ('Romance'),
       ('Thriller'),
       ('Literary Fiction'),
       ('Graphic Novels'),
       ('Education'),
       ('Politics'),
       ('Cultural Studies'),
       ('Religion'),
       ('Sports'),
       ('Music'),
       ('Law'),
       ('Psychology'),
       ('Technology'),
       ('True Crime'),
       ('Crafts & Hobbies'),
       ('Guide / How-to'),
       ('Memoir'),
       ('Adventure'),
       ('Action'),
       ('Western'),
       ('Dystopian'),
       ('Fantasy Romance'),
       ('Biographical Fiction'),
       ('Historical Fiction'),
       ('Inspirational'),
       ('Satire'),
       ('Military Fiction'),
       ('Hard Science Fiction'),
       ('Space Opera'),
       ('Short Stories'),
       ('Anthology'),
       ('Erotica'),
       ('Sagas'),
       ('Noir'),
       ('Legal Thriller'),
       ('Espionage'),
       ('Supernatural'),
       ('Action & Adventure'),
       ('Alternate History'),
       ('Comic Book'),
       ('Contemporary Fiction'),
       ('Magical Realism'),
       ('Metaphysical & Visionary'),
       ('Myths & Legends'),
       ('New Adult'),
       ('Personal Growth'),
       ('Psychological'),
       ('Social Sciences'),
       ('Parenting & Families'),
       ('Women’s Fiction'),
       ('Urban Planning');